#!/bin/bash

# =====================================================
# Script cài đặt ZSH cho Arch Linux
# Tính năng:
# - Cập nhật hệ thống
# - Xoá cấu hình ZSH cũ (nếu có) và cài lại mới
# - Thêm alias, plugins, theme
# - Tự động chuyển ZSH làm shell mặc định
# =====================================================

set -e  # Dừng script nếu có lỗi

# Màu sắc cho terminal
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_msg() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# 1. Cập nhật hệ thống
print_msg "Đang cập nhật hệ thống Arch Linux..."
sudo pacman -Syu --noconfirm

# 2. Cài đặt ZSH và các gói cần thiết
print_msg "Cài đặt ZSH và các gói bổ trợ..."
sudo pacman -S --noconfirm zsh zsh-completions zsh-syntax-highlighting zsh-autosuggestions git curl wget

# 3. Xoá cấu hình ZSH cũ nếu tồn tại
if [ -d ~/.zsh ] || [ -f ~/.zshrc ] || [ -f ~/.zsh_history ]; then
    print_warn "Phát hiện cấu hình ZSH cũ. Đang xoá..."
    rm -rf ~/.zsh ~/.zshrc ~/.zsh_history ~/.zshrc.old ~/.zshrc.pre-oh-my-zsh 2>/dev/null
    print_msg "Đã xoá cấu hình cũ."
fi

# 4. Cài đặt Oh My ZSH (framework phổ biến cho ZSH)
print_msg "Cài đặt Oh My ZSH..."
if [ -d ~/.oh-my-zsh ]; then
    print_warn "Oh My ZSH đã tồn tại. Đang xoá và cài lại..."
    rm -rf ~/.oh-my-zsh
fi

RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" -- --unattended

# 5. Cài đặt Powerlevel10k theme (đẹp, nhiều tính năng)
print_msg "Cài đặt Powerlevel10k theme..."
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# 6. Cấu hình .zshrc với các lệnh cần thiết
print_msg "Đang cấu hình .zshrc..."
cat > ~/.zshrc << 'EOF'
# ZSH configuration - Generated by zsh.sh

# Path to Oh My ZSH
export ZSH="$HOME/.oh-my-zsh"

# Theme: Powerlevel10k
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins cần thiết
plugins=(
    git
    docker
    archlinux
    systemd
    sudo
    zsh-autosuggestions
    zsh-syntax-highlighting
    colored-man-pages
    command-not-found
    extract
    history
    web-search
)

# Khởi tạo Oh My ZSH
source $ZSH/oh-my-zsh.sh

# ========== CÁC LỆNH ALIAS CẦN THIẾT ==========

# System
alias update='sudo pacman -Syu'
alias install='sudo pacman -S'
alias remove='sudo pacman -Rns'
alias clean='sudo pacman -Scc'
alias search='pacman -Ss'
alias list='pacman -Q'
alias orphans='pacman -Qtdq'
alias rmorphans='sudo pacman -Rns $(pacman -Qtdq) 2>/dev/null || echo "No orphans found"'

# ZSH
alias zshconfig='nano ~/.zshrc'
alias zshsource='source ~/.zshrc'
alias reload='source ~/.zshrc'

# Systemd
alias start='sudo systemctl start'
alias stop='sudo systemctl stop'
alias restart='sudo systemctl restart'
alias status='systemctl status'
alias enable='sudo systemctl enable'
alias disable='sudo systemctl disable'

# Docker
alias d='docker'
alias dc='docker-compose'
alias dps='docker ps'
alias di='docker images'
alias dexec='docker exec -it'

# Lệnh thông dụng
alias ls='ls --color=auto'
alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias mkdir='mkdir -pv'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Git
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias gd='git diff'
alias glog='git log --oneline --graph'

# ========== CÁC CẤU HÌNH BỔ SUNG ==========

# Lịch sử ZSH
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# Các tuỳ chọn ZSH
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt INTERACTIVE_COMMENTS

# Completion
autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# Prompt
export PS1="%n@%m: %~ $ "

# Syntax highlighting
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null

# Autosuggestions
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh 2>/dev/null

EOF

# 7. Thêm cấu hình Powerlevel10k (tự động)
print_msg "Thêm cấu hình mặc định cho Powerlevel10k..."
cat > ~/.p10k.zsh << 'EOF'
# Powerlevel10k configuration - đơn giản, hiệu quả
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs time)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
EOF

# 8. Đặt ZSH làm shell mặc định (nếu chưa)
print_msg "Đặt ZSH làm shell mặc định..."
CURRENT_SHELL=$(basename "$SHELL")
if [ "$CURRENT_SHELL" != "zsh" ]; then
    chsh -s "$(which zsh)"
    print_msg "Đã chuyển shell mặc định thành ZSH. Cần đăng xuất và đăng nhập lại để áp dụng."
else
    print_msg "ZSH đã là shell mặc định."
fi

# 9. Hoàn tất
print_msg "=========================================="
print_msg "Cài đặt ZSH hoàn tất!"
print_msg "=========================================="
print_msg "Các alias chính:"
print_msg "  - update : Cập nhật hệ thống"
print_msg "  - install <pkg> : Cài gói"
print_msg "  - remove <pkg> : Xoá gói"
print_msg "  - clean : Dọn dẹp cache pacman"
print_msg "  - reload : Tải lại .zshrc"
print_msg "  - zshconfig : Sửa .zshrc"
print_msg ""
print_msg "Để bắt đầu dùng ZSH ngay, gõ: zsh"
print_msg "Hoặc đăng xuất và đăng nhập lại để dùng ZSH mặc định."

# 10. Khởi động ZSH
if [ -z "$ZSH_VERSION" ]; then
    print_msg "Khởi động ZSH..."
    exec zsh
fi
